version: '3.1'
services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ecommerge-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ../../libs/prisma/prisma/migrations/20240723091709_schema/migration.sql:/docker-entrypoint-initdb.d/database.sql
